### ISSUE TITLE
Compile with newest typescript 5.1

### ISSUE THREAD

**Issue by Infern1** [waterbeside/colorsea#4]
Getting errors using the library:

Great docu, however fail to use it.

```
Error: node_modules/colorsea/dist/index.d.ts:333:9 - error TS2502: 'Color' is referenced directly or indirectly in its own type annotation.

333     var Color: typeof Color;
            ~~~~~


Error: node_modules/colorsea/dist/index.d.ts:343:9 - error TS2502: 'deltaE' is referenced directly or indirectly in its own type annotation.

343     var deltaE: typeof deltaE;
```

**Comment by waterbeside** [comment]
Thank you very much for pointing out the error. The issue has been fixed and you can update to the latest version (v1.2.2). If you find any more problems, please continue to submit issues to me. thank you.
